### PR TITLE
(GH-20) Add support for npm publish

### LINKED ISSUE #20: Add support for Npm.Publish
Support for the `npm publish` command would be nice.

### PR DESCRIPTION
**Pull request by pascalberger**
Add `NpmPublish` alias. Fixes #20.

Work in progress as it still needs proper testing.

### CODE REVIEW

**Comment by pascalberger** [comment]
@Philo Yes, missed to add the alias. Have added it.

**Comment by Philo** [comment]
Happy to leave any thoughts and decision to you here @pascalberger, are there any other switches that could be included for this command for the sake of completeness?

Assuming https://docs.npmjs.com/cli/publish shows the latest valid CLI usage should we add the `--access` switch also?

**Comment by pascalberger** [comment]
@Philo Added settings for `--access` and `--tag` parameters

**Comment by Philo** [comment]
Nice work @pascalberger, happy for this to be merged

**Pull request merged**
