### PR TITLE
Added NoProxy method to NpmInstallSettings

### PR DESCRIPTION
**Pull request by thisispaulsmith**
Useful addition to add the `--no-proxy` flag to an `npm install`. We have proxy issue where this is the only workaround for us.

### CODE REVIEW

**Comment by Philo** [comment]
Hi @thisispaulsmith - I cant find any references to a `--no-proxy` switch within the npm documentation.  Can you point me at a documentation reference for the switch?

**Comment by thisispaulsmith** [comment]
It doesn't look like it's actually part of npm. I remember reading a while ago that it's a pass-through option to another library that npm uses.....hence it's not documented. I can't actually find the specific library.

**Comment by Philo** [comment]
In that case maybe it is better that instead of having it added to the addin when its not official an option and instead utilise `ArgumentCustomization`?

http://www.cakebuild.net/api/Cake.Core.Tooling/ToolSettings/50AAB3A8

**Comment by Philo** [comment]
I'm closing this pull request, happy to discuss further should you feel it needed.

**Pull request closed without merging**
